services:
  wasm-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"  # Map host port 8080 to container port 8080
    volumes:
      - ./assets:/app/assets  # Mount local assets directory (for development)
    restart: unless-stopped
